#!/bin/sh
workspaces() {

ws1search="workspace\sID\s\d\s\((1)\)\s"
ws1="1"
ws2search="workspace\sID\s\d\s\((2)\)\s"
ws2="2"
ws3search="workspace\sID\s\d\s\((3)\)\s"
ws3="3"
ws4search="workspace\sID\s\d\s\((4)\)\s"
ws4="4"
ws5search="workspace\sID\s\d\s\((5)\)\s"
ws5="5"
ws6search="workspace\sID\s\d\s\((6)\)\s"
ws6="6"

# Unoccupied
un="0"

# check if Occupied
o1=$(hyprctl workspaces | rg -or '$1' $ws1search)
o2=$(hyprctl workspaces | rg -or '$1' $ws2search)
o3=$(hyprctl workspaces | rg -or '$1' $ws3search)
o4=$(hyprctl workspaces | rg -or '$1' $ws4search)
o5=$(hyprctl workspaces | rg -or '$1' $ws5search)
o6=$(hyprctl workspaces | rg -or '$1' $ws6search)

# check if Focused
f1=$(hyprctl activeworkspace | rg -or '$1' $ws1search)
f2=$(hyprctl activeworkspace | rg -or '$1' $ws2search)
f3=$(hyprctl activeworkspace | rg -or '$1' $ws3search)
f4=$(hyprctl activeworkspace | rg -or '$1' $ws4search)
f5=$(hyprctl activeworkspace | rg -or '$1' $ws5search)
f6=$(hyprctl activeworkspace | rg -or '$1' $ws6search)

ic_1=""
ic_2=""
ic_3=""
ic_4=""
ic_5=""
ic_6=""
if [ $f1 ]; then
    ic_1=""
elif [ $f2 ]; then
    ic_2=""
elif [ $f3 ]; then
    ic_3=""
elif [ $f4 ]; then
    ic_4=""
elif [ $f5 ]; then
    ic_5=""
elif [ $f6 ]; then
    ic_6=""
fi

echo 	"(box	:class \"works\"	:orientation \"h\" :spacing 5 :space-evenly \"false\" (button :onclick \"hyprctl dispatch workspace $ws1\"	:class	\"$un$o1$f1\"	\"$ic_1\") (button :onclick \"hyprctl dispatch workspace $ws2\"	:class \"$un$o2$f2\"	 \"$ic_2\") (button :onclick \"hyprctl dispatch workspace $ws3\"	:class \"$un$o3$f3\" \"$ic_3\") (button :onclick \"hyprctl dispatch workspace $ws4\"	:class \"$un$o4$f4\"	\"$ic_4\") (button :onclick \"hyprctl dispatch workspace $ws5\"	:class \"$un$o5$f5\" \"$ic_5\")  (button :onclick \"hyprctl dispatch workspace $ws6\"	:class \"$un$o6$f6\" \"$ic_6\"))"

}
workspaces
