theme = "rose_pine"

[editor]
line-number = "relative"
text-width = 120

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w"  # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-a = "select_all"
"ret" = ["move_line_down", "goto_first_nonwhitespace"] # Maps the enter key to move to start of next line
"tab" = "indent"
"S-tab" = "unindent"
C-u = ["page_up", "align_view_center"]  # Align center on page up
C-d =  ["page_down", "align_view_center"]  # Align center on page up
g = { a = "code_action" } # Maps `ga` to show possible code actions
X = "extend_line_above"
D = "delete_char_backward"

# move lines up & down
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]