hwdec-codecs=all

hwdec=nvdec
gpu-api=vulkan
gpu-context=wayland
#profile=high-quality
cache=yes

volume=75
save-position-on-quit=yes
save=yes
keep-open=yes

sub-visibility=yes
enable-subtitles=yes
sub-auto=fuzzy
alang=jpn
alang: kor, kr, en
slang: kor, kr, en

ytdl-format=bestvideo+bestaudio/best
screenshot-format=png
screenshot-high-bit-depth=yes

# HDR (if you use HDR display)
#hdr-compute-peak=yes
#tone-mapping=bt.2390
